module.exports.states = {
    0: ['Alabama', 'Montgomery'],
    1: ['Alaska', 'Juneau'],
    2: ['Arizona', 'Phoenix'],
    3: ['Arkansas', 'Little Rock'],
    4: ['California', 'Sacramento'],
    5: ['Colorado', 'Denver'],
    6: ['Connecticut', 'Hartford'],
    7: ['Delaware', 'Dover'],
    8: ['Florida', 'Tallahassee'],
    9: ['Georgia', 'Atlanta'],
    10: ['Hawaii', 'Honolulu'],
    11: ['Idaho', 'Boise'],
    12: ['Illinois', 'Springfield'],
    13: ['Indiana', 'Indianapolis'],
    14: ['Iowa', 'Des Moines'],
    15: ['Kansas', 'Topeka'],
    16: ['Kentucky', 'Frankfort'],
    17: ['Louisiana', 'Baton Rouge'],
    18: ['Maine', 'Augusta'],
    19: ['Maryland', 'Annapolis'],
    20: ['Massachusetts', 'Boston'],
    21: ['Michigan', 'Lansing'],
    22: ['Minnesota', 'Saint Paul'],
    23: ['Mississippi', 'Jackson'],
    24: ['Missouri', 'Jefferson City'],
    25: ['Montana', 'Helena'],
    26: ['Nebraska', 'Lincoln'],
    27: ['Nevada', 'Carson City'],
    28: ['New Hampshire', 'Concord'],
    29: ['New Jersey', 'Trenton'],
    30: ['New Mexico', 'Santa Fe'],
    31: ['New York', 'Albany'],
    32: ['North Carolina', 'Raleigh'],
    33: ['North Dakota', 'Bismarck'],
    34: ['Ohio', 'Columbus'],
    35: ['Oklahoma', 'Oklahoma City'],
    36: ['Oregon', 'Salem'],
    37: ['Pennsylvania', 'Harrisburg'],
    38: ['Rhode Island', 'Providence'],
    39: ['South Carolina', 'Columbia'],
    40: ['South Dakota', 'Pierre'],
    41: ['Tennessee', 'Nashville'],
    42: ['Texas', 'Austin'],
    43: ['Utah', 'Salt Lake City'],
    44: ['Vermont', 'Montpelier'],
    45: ['Virginia', 'Richmond'],
    46: ['Washington', 'Olympia'],
    47: ['West Virginia', 'Charleston'],
    48: ['Wisconsin', 'Madison'],
    49: ['Wyoming', 'Cheyenne']
 };
