category: GAMES_AND_TRIVIA
defaultLocale: en
localizedSettings:
  developerEmail:
  developerName:
  displayName: AOG Education
  fullDescription:
  privacyPolicyUrl:
  pronunciation: AOG Education
  shortDescription:
  smallLogoImage:
  termsOfServiceUrl:
projectId: test-project-e40c9
# projectId: step-capstone
usesInteractiveCanvas: true