category: GAMES_AND_TRIVIA
defaultLocale: en
localizedSettings:
    developerEmail: AOG2@ElectricBoogaloo.aol
    developerName: STEP SQUAD
    displayName: AOG Education
    pronunciation: AOG Education
    voice: male_3
projectId: step-capstone
usesInteractiveCanvas: true
