category: GAMES_AND_TRIVIA
defaultLocale: en
localizedSettings:
    developerEmail: AOG2@ElectricBoogaloo.aol
    developerName: STEP SQUAD
    displayName: AOG Education
    fullDescription:
    privacyPolicyUrl:
    pronunciation: AOG Education
    shortDescription:
    smallLogoImage:
    termsOfServiceUrl:
projectId: step-capstone
usesInteractiveCanvas: true
