module.exports.countries = [
    ['Nigeria', 'Abuja', '002'],
    ['Ethiopia', 'Addis Ababa', '002'],
    ['Turkey', 'Ankara', '145'],
    ['Thailand', 'Bangkok', '035'],
    ['China', 'Beijing', '142'],
    ['Germany', 'Berlin', '150'],
    ['Colombia', 'Bogotá', '005'],
    ['Brazil', 'Brasilia', '005'],
    ['Egypt', 'Cairo', '002'],
    ['Bangladesh', 'Dhaka', '034'],
    ['Tanzania', 'Dodoma', '002'],
    ['Vietnam', 'Hanoi', '035'],
    ['Pakistan', 'Islamabad', '034'],
    ['Indonesia', 'Jakarta', '035'],
    ['Sudan', 'Khartoum', '002'],
    ['United Kingdom', 'London', '150'],
    ['Spain', 'Madrid', '150'],
    ['Philippines', 'Manila', '035'],
    ['Mexico', 'Mexico City', '019'],
    ['Russia', 'Moscow', '151'],
    ['Kenya', 'Nairobi', '002'],
    ['Myanmar', 'Naypyidaw', '142'],
    ['India', 'New Delhi', '034'],
    ['France', 'Paris', '150'],
    ['South Africa', 'Pretoria', '002'],
    ['Italy', 'Rome', '150'],
    ['South Korea', 'Seoul', '030'],
    ['Iran', 'Tehran', '142'],
    ['Japan', 'Tokyo', '030'],
    ['United States', 'Washington, D.C.', '021']
];
